Algoritmo "ex1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/01/2022
Var
// Seção de Declarações das variáveis 
  produto1, produto2, genero : caractere
  preco1, preco2 : real
  idade, codigo : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   produto1 <- "Computador"
   produto2 <- "TV"
   genero <- "M"
   preco1 <- 2100.5
   preco2 <- 1830.0
   idade <- 20
   codigo <- 5291
   
   escreval("O produto:")
   escreval("O produto ", produto1," custa R$",preco1)
   escreval("O produto ",produto2," custa R$",preco2)
   escreval
   escreval("Codigo =",codigo)
   escreval
   escreval("Dados da passoa:")
   escreval("genero: ",genero)
   escreval("Idade: ",idade)

Fimalgoritmo