Algoritmo "Ex20_multiplos"
// Fazer um programa para ler dois números inteiros, e dizer se um número é múltiplo do outro. Os
//números podem ser digitados em qualquer ordem.

// Data atual  : 01/02/2022
Var

   n1, n2: inteiro

Inicio

   escreval("Digite 2 numeros inteiros: ")
   leia(n1)
   leia(n2)

   se (n1 % N2 = 0 ) ou (n2 % n1 = 0) entao
      escreval("São multiplos")
   senao
      escreva("Não são multiplos")
   fimse


Fimalgoritmo