Algoritmo "Ex5_soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Problema "soma"
//Fazer um programa para ler dois valores inteiros X e Y, e depois mostrar na tela o valor da soma destes
//números.
// Data atual  : 19/01/2022
Var

   X, Y, soma: Inteiro

Inicio

   escreva("Informe um valor X: ")
   leia(X)
   escreva("Informe um valor Y: ")
   leia(Y)
   soma <- (X + Y)
   escreval
   escreva("O resultado da soma entre ",X," e ",Y," é: ",soma)


Fimalgoritmo